[features]
seeds = true
skip-lint = false
[programs.localnet]
deposit = "7YKyo13HtdB823RiWHacDR74wc7VeU8vkMZGJDP2nSUB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/ivmidable/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test.validator]
url = "https://api.devnet.solana.com"
[test]
startup_wait = 20000

# Token Metadata program
[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

# Dex program
[[test.validator.clone]]
address = "EoTcMgcDRTJVZDMZWBoU6rhYHZfkNTVEAfz3uUJRcYGj"

